
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdtomvatsgueqyylonmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkdG9tdmF0c2d1ZXF5eWxvbm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNTEwMjMsImV4cCI6MjA2MTgyNzAyM30.UUWniA5lWVWd7RcvZT_GuDzTBg24XTbiEZQcAQzp9DU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
